### ISSUE TITLE
Repositório como publico

### ISSUE THREAD

**Issue by Kenedw** [stfn0/PDI#1]
**Apesar dos apesares de você ser um minino tímido, nossos colaboradores estão preparando uma linda documentação para este trabalho, fazendo com que ele seja uma grande fonte de conhecimento para as futuras gerações de PDI.
Analisando estes e alguns outros pontos, fica claro o motivo e precisão deste pedido, o povo quer, o povo deseja, ESTE REPOSITÓRIO COMO PUBLICO!!!**

**Comment by stfn0** [comment]
Pronto! Só não coloca teus códigos quebrados como público.
